#spring:
#  datasource:
#    url: jdbc:postgresql://127.0.0.1:5432/postgres
#    password: new_password
#    username: postgres
#  jpa:
#    hibernate:
#      ddl-auto: update
#      format_sql: true
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#
#
#
#
#
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
download:
  path: ${ENV_DOWNLOAD_PATH:http://localhost:8080/download}